name: Star Event Workflow

on:
  watch: # This event is triggered when a repository is starred or unstarred.

jobs:
  log-star-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log star event
        run: |
          echo "⭐ A user has starred or unstarred the repository."
          echo "Event information:"
          cat $GITHUB_EVENT_PATH
